# Default initial positions for robot_harambe_v0.3's ros2_control fake system

initial_positions:
  left_elbow_pitch_joint_X6: 0
  left_shoulder_pitch_joint_X6: 0
  left_shoulder_roll_joint_X6: 0
  left_shoulder_yaw_joint_X4: 0
  left_wrist_roll_joint_X4: 0
  left_wrist_yaw_joint_X4: 0