<?xml version="1.0"?>
<package format="3">
  <name>harambe_gz_policy_plugin</name>
  <version>0.1.0</version>
  <description>Gazebo Harmonic plugin that runs ONNX RL policy with PD control and velocity limiting</description>
  <maintainer email="your.email@example.com">LD Robots</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>ros-jazzy-gz-sim-vendor</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
